development:
  adapter: postgresql
  database: givey_dev_v2
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  database: givey_staging
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: givey_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: givey_production
  pool: 5
  timeout: 5000
